// ui/images.slint

struct ImageData {
    id: string,
    tag: string,
    size: string,
    created: string,
    in_use: bool,
}

component Button inherits Rectangle {
    in property <string> text;
    in property <bool> active: false;
    in property <bool> enabled: true;
    in property <length> size_w: 64px;
    in property <length> size_h: 32px;
    in property <brush> bg: #2e3030;
    callback clicked <=> touch.clicked;

    height: size_h;
    width: size_w;
    background: !root.enabled ? #4b5563 : root.active ? #0ea5e9 : bg;
    border-radius: 6px;
    border-width: root.active ? 2px : 0px;
    border-color: #0ea5e9;

    touch := TouchArea {
        enabled: root.enabled;
    }

    Text {
        text: root.text;
        color: !root.enabled ? #9ca3af : #ffffff;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 14px;
        x: 8px;
        y: 0px;
        width: parent.width - 16px;
        height: parent.height;
    }
}

component ErrorMessage inherits Rectangle {
    in property <string> text;
    in property <brush> bg;
    in property <brush> text-color;

    background: bg;
    border-radius: 8px;
    padding-left: 16px;
    padding-right: 16px;

    Text {
        text: text;
        color: text-color;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 14px;
    }
}

component StatusIndicator inherits Rectangle {
    in property <bool> in_use;

    width: 12px;
    height: 12px;
    border-radius: 6px;
    background: in_use ? #10b981 : #ef4444;
}

component ImageItem inherits Rectangle {
    in property <ImageData> image;
    callback image-action(string);

    background: #2e3030;
    border-radius: 8px;
    height: 80px;

    HorizontalLayout {
        padding: 16px;
        spacing: 16px;
        alignment: space-between;

        HorizontalLayout {
            spacing: 16px;
            StatusIndicator {
                in_use: image.in_use;
            }

            VerticalLayout {
                spacing: 4px;
                alignment: start;

                Text {
                    text: image.tag;
                    color: #ffffff;
                    font-size: 16px;
                    font-weight: 600;
                }

                HorizontalLayout {
                    spacing: 12px;

                    Text {
                        text: "Tamanho: " + image.size;
                        color: #9ca3af;
                        font-size: 14px;
                    }
                }
            }
        }

        HorizontalLayout {
            spacing: 12px;

            VerticalLayout {
                alignment: center;

                Text {
                    text: image.in_use ? "Em uso" : "Não utilizado";
                    color: image.in_use ? #10b981 : #ef4444;
                    font-size: 12px;
                    font-weight: 600;
                }

                Text {
                    width: 64px;
                    text: image.created;
                    color: #6b7280;
                    font-size: 10px;
                }
            }

            Rectangle {
                width: 140px;
                HorizontalLayout {
                    alignment: center;
                    spacing: 12px;

                    Button {
                        text: "Deletar";
                        bg: #1A1B1B;
                        enabled: !image.in_use;
                        clicked => {
                            image-action("remove");
                        }
                    }
                }
            }
        }
    }
}

export component ImagesList inherits VerticalLayout {
    in property <[ImageData]> images;
    in property <string> image-list-error;
    in property <string> success_message: "";
    in property <string> error_in_use_message: "";
    in property <string> error_other_message: "";

    callback refresh-clicked();
    callback image-action(string, string);

    padding: 24px;
    spacing: 24px;

    VerticalLayout {
        spacing: 20px;
        height: 64px;
        padding-top: 8px;
        vertical-stretch: 0;
        alignment: center;

        HorizontalLayout {
            alignment: space-between;

            Text {
                text: "Imagens";
                font-size: 24px;
                font-weight: 600;
            }

            // Button {
            //     text: "Atualizar";
            //     size_w: 128px;
            //     clicked => {
            //         refresh-clicked();
            //     }
            // }
            if root.image-list-error != "": ErrorMessage {
                bg: #ef444420;
                text: "Erro: " + root.image-list-error;
                text-color: #ef4444;
            }

            if root.success_message != "": ErrorMessage {
                bg: #10b98120;
                text: root.success_message;
                text-color: #10b981;
            }

            if root.error_in_use_message != "": ErrorMessage {
                bg: #ef444420;
                text: root.error_in_use_message;
                text-color: #ef4444;
            }

            if root.error_other_message != "": ErrorMessage {
                bg: #f9731620;
                text: root.error_other_message;
                text-color: #f97316;
            }
        }
    }

    if images.length == 0: Rectangle {
        background: #2e3030;
        border-radius: 8px;
        height: 100px;

        Text {
            text: "Nenhuma imagem encontrada";
            color: #9ca3af;
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 16px;
        }
    }

    if images.length > 0: Flickable {
        vertical-stretch: 1;

        VerticalLayout {
            spacing: 12px;

            for image in images: ImageItem {
                image: image;
                image-action(action) => {
                    image-action(image.id, action);
                }
            }
        }
    }
}
